"""
taskflow_primitive_obsession - Anti-pattern example demonstrating primitive
obsession and anemic domain model

This project demonstrates the practical application of the building-blocks
library in a real-world scenario.

Architecture Layers:
- Domain: Pure business logic and rules
- Application: Use cases and orchestration
- Infrastructure: External system adapters
- Presentation: User interfaces

Generated by: Building Blocks Project Creator v1.2.0
Author: Glauber Brennon
Created: 2025-06-18 05:43:11 UTC
"""

__version__ = "0.1.0"
__author__ = "Glauber Brennon"
__email__ = "glauberbrennon@gmail.com"

# Package exports will be added as components are implemented
__all__ = []
