name: "Setup Poetry"
description: "Checkout, setup Python, cache and install Poetry dependencies"
inputs:
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      run: pip install poetry
      shell: bash
    - name: Cache pip and Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ inputs.python-version }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ inputs.python-version }}
    - name: Install dependencies
      run: poetry install
      shell: bash
