name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint (ruff, black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: '3.9'
      - name: Run Ruff (lint)
        run: poetry run ruff check src tests examples
      - name: Run Black (check)
        run: poetry run black --check src tests examples

  typecheck:
    name: Type Check (mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: '3.9'
      - name: Run mypy
        run: poetry run mypy src tests examples

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: '3.9'
      - name: Run pytest with coverage (fail if <85%)
        run: poetry run pytest --cov=src --cov-report=xml --cov-fail-under=85

  security:
    name: Security (bandit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: '3.9'
      - name: Run bandit
        run: poetry run bandit -r src
